### ISSUE TITLE
Kernel Sources not loading in Developmental Container

### ISSUE THREAD

**Issue by kshitizbakshi** [flatcar/Flatcar#106]
**Description**

We are not able to get sources for the kernel in the Flatcar Development container. Following instructions from [this page](https://docs.flatcar-linux.org/os/kernel-modules/), we're able to successfully start the container, but running `emerge -gKv coreos-sources` errors out. 

For at least one older version (2247.5.0), I was able to get the kernel sources to load and build modules, but ran in to other weird errors later. (discussion in comments). Could it be that the older version is also fetching sources from CoreOS' servers (as the error logs for this ticket suggest?)

**Impact**

We're not able to compile custom kernel modules, among which the most critical is NVIDIA GPU driver modules, without which we cannot enable using Flatcar.

**Environment and steps to reproduce**

1. **Set-up**: Flatcar Stable 2345.3.1, running on AWS P3.2xlarge EC2 Instance, and using the development container of version 2345.3.1
2. **Task**: Loading the kernel modules
3. **Action(s)**: [ sequence of actions that triggered the bug, see example below ]
  a. Launched a new development container following [this page](https://docs.flatcar-linux.org/os/kernel-modules/).
  b. Ran `emerge -gKv coreos-sources` after `emerge-gitclone`
4. **Error**: Got these logs and a non-zero exit code:
```
flatcardevelopercontainer ~ # emerge -gKv coreos-sources


!!! Error fetching binhost package info from 'http://builds.developer.core-os.net/boards/amd64-usr/2345.3.1/pkgs/'
!!! HTTP Error 404: Not Found



!!! Error fetching binhost package info from 'http://builds.developer.core-os.net/boards/amd64-usr/2345.3.1/toolchain/'
!!! HTTP Error 404: Not Found


These are the packages that would be merged, in order:

Calculating dependencies |Unable to enable loopback interface: EPERM
 \Unable to enable loopback interface: EPERM
 -Unable to enable loopback interface: EPERM
 \Unable to enable loopback interface: EPERM
 |Unable to enable loopback interface: EPERM
 |Unable to enable loopback interface: EPERM
 /Unable to enable loopback interface: EPERM
 -Unable to enable loopback interface: EPERM
 \Unable to enable loopback interface: EPERM
 |Unable to enable loopback interface: EPERM
 |Unable to enable loopback interface: EPERM
... done!

emerge: there are no binary packages to satisfy "coreos-sources".

emerge: searching for similar names...
emerge: Maybe you meant any of these: sys-kernel/coreos-modules, coreos-base/coreos-dev, coreos-base/coreos-au-key?
flatcardevelopercontainer ~ # echo $?
1
```

**Expected behavior**
No errors, and kernel sources to normally fetch.

**Additional information**

Please help, and let me know if more information is needed!

**Comment by mukteshkrmishra** [comment]
On a cursory look, it seems there are no bin host packages avail for version `2345.3.1`.

http://builds.developer.core-os.net/boards/amd64-usr/

Can you try with any other stable version?

**Comment by kshitizbakshi** [comment]
@mukteshkrmishra yeah, that's what I thought too, but another weird thing is it looking for sources on the CoreOS servers, which made me feel that maybe there's a bug that the Flatcar folks can fix? There is no CoreOS version 2345.3.1, which could explain the failure for that version and not the older versions.

I tried out with Flatcar 2247.5.0, where emerging the sources succeeded, and I was able to build the kernel modules, but they won't load at runtime with these errors:

```
Kernel module load error: Exec format error
Kernel messages:
[ 1188.728917] nvidia: version magic '4.19.78-coreos SMP mod_unload ' should be '4.19.78-flatcar SMP mod_unload '
```
This does make it seem like the module was built against a CoreOS kernel signature whereas at runtime it needs a Flatcar one.

**Comment by pothos** [comment]
Hello,

thanks for reporting!

`http://builds.developer.core-os.net/boards/…` is the wrong `PORTAGE_BINHOST` URL in `/etc/portage/make.conf`.

Until we fix the issue, please replace it with `https://storage.googleapis.com/flatcar-jenkins/boards/…`.

**Comment by pothos** [comment]
The PR is merged but the fix will only land in the next releases. So please change the URLs in `/etc/portage/make.conf` manually in the development container until then.

**Comment by kshitizbakshi** [comment]
Thanks a ton @pothos for the great turnaround time! Your workaround worked and I was able to build and deploy NVIDIA Drivers on Flatcar. :) 

I see that the fix is also merged; would you be able to tell me which Flatcar stable version this would roll out with? That way we'd be able to make the workaround conditional in our codebases.

**Comment by pothos** [comment]
Every new release from now on will include the change, on any channel because we included the fix in every channel. Assuming you are on the Stable channel, then this workaround is only needed for versions 2345.3.1 and below.

**Comment by vbatts** [comment]
hah. I just found my way here while working through the docs 
https://github.com/flatcar-linux/docs/pull/89#issuecomment-630440874

**Comment by rikatz** [comment]
Hey, about this issue :D How can we make NVidia drivers available in flatcar (maybe as a container) so we can use this also for our IA loads (instead of using CentOS as nodes :/ )

@pothos do you have any doc into how you made this? Thank you!!

**Comment by pothos** [comment]
This issue here was fixed in the last Stable release but if you want to build it for an older release, change the URLs in `/etc/portage/make.conf` (see https://github.com/flatcar-linux/scripts/pull/58/files).

See here on how to build custom kernel modules, this should work for NVidia, too: https://docs.flatcar-linux.org/os/kernel-modules/

**Comment by vbatts** [comment]
@rikatz like @pothos mentioned with the docs link, I recently did similar to get a flatcar stable machine to have wireguard modules https://gist.github.com/vbatts/9af92a341611751dc3a157f204a84973

**Comment by jbanety** [comment]
Hi,
For those who still have problems, I added the linux capabilities ` --capability=CAP_NET_ADMIN` to allow the container to work.    
```
sudo systemd-nspawn \    
    --capability=CAP_NET_ADMIN    
    --bind=/usr/lib64/modules \   
    --image=flatcar_developer_container.bin
```
