### ISSUE TITLE
`systemd-sysupdate.service` and `systemd-sysupdate-reboot.service` are in a failed state

### ISSUE THREAD

**Issue by tormath1** [flatcar/Flatcar#1979]
## Description

With systemd upgrade on current Alpha / Beta (>=4515), those two units are in a failed state:
```
$ systemctl --failed
  UNIT                             LOAD   ACTIVE SUB    DESCRIPTION
● systemd-sysupdate-reboot.service loaded failed failed Reboot Automatically After System Update
● systemd-sysupdate.service        loaded failed failed Automatic System Update

Legend: LOAD   → Reflects whether the unit definition was properly loaded.
        ACTIVE → The high-level unit activation state, i.e. generalization of SUB.
        SUB    → The low-level unit activation state, values depend on unit type.

2 loaded units listed.
```

This is because the `systemd-sysupdate.timer` unit is enabled by default following the systemd upgrade.

## Impact

This is harmless, this happens when there's no sysext image candidate for upgrade:
```
 systemd-sysupdate[3835]: No transfer definitions found.
```

**Comment by pothos** [comment]
While this was important for Beta/Alpha, it's also nice for LTS/Stable and we should backport https://github.com/flatcar/init/pull/139 on an init-backport branch

**Comment by pothos** [comment]
For LTS the file still needs to be called `.conf`

**Comment by pothos** [comment]
Ah, same for stable, so we need a backport branch...

**Comment by pothos** [comment]
Done, would still be nice to have this working upstream without failing the unit. Skipping the unit is not nice because that means one can't use drop-ins for components but they would need their own full units.

**Comment by tormath1** [comment]
Solved with latest release - I don't see the failed units anymore.

**Comment by stumbaumr** [comment]
Still happens for us on current stable 4593.2.0.
See details here: https://github.com/flatcar/Flatcar/issues/1983#issuecomment-4333070622

**Comment by tormath1** [comment]
Thanks @stumbaumr for raising this, it's a harmless issue, no need to switch to LTS. We're investigating again to fix this in the next release.

**Comment by michal-kuzak** [comment]
Still on 4593.2.3

**Comment by tormath1** [comment]
> Still on 4593.2.3

@michal-kuzak let's try to solve this upstream: https://github.com/systemd/systemd/pull/42750

**Comment by der-eismann** [comment]
@tormath1 could you please apply Lennart's comments on your PR so this can get merged?

**Comment by tormath1** [comment]
> [@tormath1](https://github.com/tormath1) could you please apply Lennart's comments on your PR so this can get merged?

Hi @der-eismann thanks for the heads-up. I finally got time to rework this, I initially wanted to backport the patch to systemd 257 (Flatcar's systemd version on Stable) but it turned to be too much patches to carry on.
I'm now revisiting this with more recent systemd version. Let's see :)

**Comment by ader1990** [comment]
Hello, I got this error on the latest version as well.

@tormath1 any chance this can get in systemd? or we can just patch systemd on our own? (although systemd is now in portage stable, so that might mess things up a little).

I can also help on the systemd PR review comments, if needed.

Thanks.

**Comment by tormath1** [comment]
> Hello, I got this error on the latest version as well.
> 
> [@tormath1](https://github.com/tormath1) any chance this can get in systemd? or we can just patch systemd on our own? (although systemd is now in portage stable, so that might mess things up a little).
> 
> I can also help on the systemd PR review comments, if needed.
> 
> Thanks.

Hey @ader1990 the PR is opened for review and tested on the Flatcar side. Happy if you can have a look to the upstream PR :) https://github.com/systemd/systemd/pull/42750
