### ISSUE TITLE
K8s 1.20 docker deprecation: simplify use of containerd for k8s

### ISSUE THREAD

**Issue by t-lo** [flatcar/Flatcar#284]
**Current situation**
Kubernetes 1.20 deprecated docker use; docker is still supported but issues a deprecation warning; support will be dropped in a future release. While we ship a CRI compatible containerd which can be used by kubernetes with some effort, it's not straightforward and it does not work out of the box.

**Impact**
* users are required to entirely replace the systemd unit of containerd shipped with Flatcar Container Linux in order to make k8s use containerd directly.
* alternatively, users are forced to continue using docker which has ceased to be the recommended set-up by upstream k8s.

**Ideal future situation**
* Immediate mitigation: documentation / example configuration is available on how to provision / set up Flatcar with containerd supporting k8s directly.
* Mid-term resolution: update containerd service file (and possibly containerd components / dependencies) to make k8s on containerd work out of the box (also see #283)

**Implementation options**
- [x]  Provide docs and example config for setting up containerd correctly to support running without docker (here: https://github.com/kinvolk/flatcar-docs/tree/main/docs/container-runtimes)
- [x]  make k8s on containerd work out of the box

**Comment by invidian** [comment]
Following Ignition configuration can be used to prepare `containerd` to be used by `kubelet` on Flatcar Beta (2705.1.0):
```yaml
storage:
  files:
  - path: /etc/containerd/config.toml
    filesystem: root
    mode: 0600
    contents:
      inline: |
        # persistent data location
        root = "/var/lib/containerd"
        # runtime state information
        state = "/run/docker/libcontainerd/containerd"
        # set containerd as a subreaper on linux when it is not running as PID 1
        subreaper = true
        # set containerd's OOM score
        oom_score = -999
        # CRI plugin listens on a TCP port by default
        disabled_plugins = []

        # grpc configuration
        [grpc]
        address = "/run/docker/libcontainerd/docker-containerd.sock"
        # socket uid
        uid = 0
        # socket gid
        gid = 0

        [plugins.linux]
        # shim binary name/path
        shim = "containerd-shim"
        # runtime binary name/path
        runtime = "runc"
        # do not use a shim when starting containers, saves on memory but
        # live restore is not supported
        no_shim = false
        # display shim logs in the containerd daemon's log output
        shim_debug = true
systemd:
  units:
  - name: containerd.service
    enabled: true
    dropins:
    - name: 10-use-custom-config.conf
      contents: |
        [Service]
        Environment=CONTAINERD_CONFIG=/etc/containerd/config.toml
        ExecStart=
        ExecStart=/usr/bin/env PATH=$${TORCX_BINDIR}:$${PATH} $${TORCX_BINDIR}/containerd --config $${CONTAINERD_CONFIG}
```

Diff from base `containerd` config:
```diff
diff --git a/run/torcx/unpack/docker/usr/share/containerd/config.toml b/etc/containerd/config.toml
index 2b37f3c..54969bd 100644
--- a/run/torcx/unpack/docker/usr/share/containerd/config.toml
+++ b/etc/containerd/config.toml
@@ -7,7 +7,7 @@ subreaper = true
 # set containerd's OOM score
 oom_score = -999
 # CRI plugin listens on a TCP port by default
-disabled_plugins = ["cri"]
+disabled_plugins = []

 # grpc configuration
 [grpc]
```

This configuration keeps backward-compatibility with Docker.

To tell `kubelet` to use containerd, make sure `kubelet` process has access to following directories on host file system:
- `/run/docker/libcontainerd/`
- `/var/lib/containerd`

And that it has access to the following binaries on host file system and that they are included in PATH:
- `/run/torcx/unpack/docker/bin/containerd-shim-runc-v1`
- `/run/torcx/unpack/docker/bin/containerd-shim-runc-v2` (optional?)

Then, add the following flags to `kubelet`:
- `--container-runtime=remote`
- `--container-runtime-endpoint=unix:///run/docker/libcontainerd/docker-containerd.sock`

#

If you don't need Docker compatibility, containerd config override can be just an empty file to use all defaults from upstream.

Then, make sure `kubelet` has access to the following directories on host file system:
- `/run/containerd`
- `/var/lib/containerd`

And that it has access to the following binaries on host file system and that they are included in PATH:
- `/run/torcx/unpack/docker/bin/containerd-shim-runc-v1`
- `/run/torcx/unpack/docker/bin/containerd-shim-runc-v2` (optional?)

Then, add the following flags to `kubelet`:
- `--container-runtime=remote`
- `--container-runtime-endpoint=unix:///run/containerd/containerd.sock`

**Comment by t-lo** [comment]
PR for Flatcar docs (than you @invidian !) : https://github.com/kinvolk/flatcar-docs/pull/132

**Comment by pothos** [comment]
Docs to manually use containerd with Kubernetes are published under https://kinvolk.io/docs/flatcar-container-linux/latest/container-runtimes/switching-from-docker-to-containerd-for-kubernetes/

**Comment by alban** [comment]
Do you know which version of Kubernetes is supported by the containerd in Flatcar? It would be nice to add that in the doc (or explain where to get that information)

There are some support matrix at https://github.com/containerd/cri/#support-metrics but I am not sure if they are up-to-date, now that containerd/cri has been moved to containerd/containerd.

**Comment by pothos** [comment]
About _make k8s on containerd work out of the box_: The next Stable release will enable the containerd cri plugin. The kubelet still needs to know which socket path to use but this seems to be common and is easy to set. We can switch to the default containerd socket path, too, if that helps but it is a breaking change.

**Comment by f-bn** [comment]
Do we still need to empty the containerd configuration file (like explained in docs) with the lastest release of Flatcar (2605.10.0) then ?

**Comment by pothos** [comment]
No, you can use the shipped configuration if you want to keep Docker around (the first case outlined in the docs _Running containerd with CRI plugin enabled alongside with Docker_).

I think we can remove the first case in the docs again and call out that this is the default now.

**Comment by f-bn** [comment]
Sorry, I was not clear in my question, I would say, do we still need to empty the configuration file for Kubernetes usage only (such as mentionned in the documentation) if CRI is enabled by default in the lastest Flatcar release.

**Comment by pothos** [comment]
You don't need to set up an empty containerd configuration, but you can if you want to brick Docker and use the default socket location for containerd.
The difference between the Flatcar configuration and the empty configuration is the socket path for the `kubelet --container-runtime-endpoint=` parameter.

Docs PR: https://github.com/kinvolk/flatcar-docs/pull/146

**Comment by f-bn** [comment]
Thanks for your answer ! Will dive into it ;)

**Comment by hakman** [comment]
@pothos If the purpose of this issue is to simplify use of containerd for k8s setups, this should also change the default socket location as most tools (like `ctr`, `crictl`, ...) expect it to be in `/run/containerd/containerd.sock`. If anyone wants to use those becomes a hassle to always specify `--address ...`.
Is there any way to use `/run/containerd/containerd.sock` as default and create a symlink to `/run/docker/libcontainerd/docker-containerd.sock`?

**Comment by pothos** [comment]
I agree, it would be best to migrate to the new socket location. Does it work for you to create a symlink the other way round in the mean time?

**Comment by hakman** [comment]
Thanks @pothos.
At the moment I am thinking about a more permanent fix for kOps, like overriding the config file (which is a nice thing to have anyway). Adding a symlink that may not work in the future would generate issues for those that use kOps with Flatcar.

**Comment by pothos** [comment]
Filed a PR to switch the socket location and create a symlink for the old location: https://github.com/kinvolk/coreos-overlay/pull/771

**Comment by hakman** [comment]
Thanks for the update @pothos.
May want to sync the service file with the [upstream](https://github.com/containerd/containerd/blob/master/containerd.service), at least add `Type=notify`.

**Comment by pothos** [comment]
Thanks, added it

**Comment by Jasper-Ben** [comment]
I am not sure the steps described at https://kinvolk.io/docs/flatcar-container-linux/latest/container-runtimes/switching-from-docker-to-containerd-for-kubernetes/ currently work (2605.12.0).

When trying to init a kubernetes cluster using kubeadm I still get the following Warning:
`W0203 12:46:11.599434   84665 kubelet.go:205] detected "cgroupfs" as the Docker cgroup driver, the provided value "systemd" in "KubeletConfiguration" will be overrided`

I defined the following init configuration
```
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
controlPlaneEndpoint: foo.bar
kubernetesVersion: $RELEASE
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
cgroupDriver: systemd
```
and called it with `kubeadm init --config conf.yaml --cri-socket=/run/containerd/containerd.sock --upload-certs`


When trying to disable Docker completely as described on the page (after fixing the systemd drop-in*), I still get the same warning

*TORCX_BINDIR is not defined and AFAIK variables defined in "Environment" need to be called as $FOO not $${FOO} in ExecStart

**Comment by pothos** [comment]
I think you shouldn't set `cgroupDriver: systemd` unless you also set it for containerd (and I think it has a bug about self freezing cgroups). The default is `cgroupfs`.

About disabling Docker, you don't need this. You can use the default containerd config that Flatcar has without any unit drop-ins. The socket location is now under `/run/containerd/containerd.sock` by default. I think I'll file a PR to remove the last section of the docs.

**Comment by Jasper-Ben** [comment]
So just to be clear: Do I need to change the kubelet systemd service to add the flags `--container-runtime=remote --container-runtime-endpoint=unix:///run/containerd/containerd.sock` or should it just work without any modifications whatsoever?

**Comment by pothos** [comment]
I think the kubelet parameters need to have it passed explicitly but I didn't check the defaults. No modifications in Flatcar's containerd are needed.

Done here: https://github.com/kinvolk/flatcar-docs/pull/153

**Comment by Jasper-Ben** [comment]
I am still getting the following warnings and healthz fails:
```
[preflight] Running pre-flight checks
        [WARNING Service-Docker]: docker service is not enabled, please run 'systemctl enable docker.service'
        [WARNING IsDockerSystemdCheck]: detected "cgroupfs" as the Docker cgroup driver. The recommended driver is "systemd". Please follow the guide at https://kubernetes.io/docs/setup/cri/
```

So again, one by one just to cover all the bases:
- running flatcar linux stable (2605.12.0)
- `/etc/systemd/system/kubelet.service.d/10-kubeadm.conf` contains:
```
Environment="KUBELET_KUBECONFIG_ARGS=--bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf --container-runtime=remote --container-runtime-endpoint=unix:///run/containerd/containerd.sock"
```
- init config contains:
```
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
controlPlaneEndpoint: foo.bar
kubernetesVersion: $RELEASE
```
- kubeadm called with `kubeadm init --config conf.yaml --upload-certs`

Of course there is a chance of the whole setup being bricked now, after a multitude of kubeadm resets & inits. So if you say this should definitely work, I'd have to drive to the office first to reinstall :sweat_smile: 

P.S.:Forgot the `--cri-socket=/run/containerd/containerd.sock` which at least took care of the docker warnings. still no healthy kubelet though.

**Comment by pothos** [comment]
What is the error message? Can you still run docker containers? I don't know what the rest of your kubelet.service file has.
In doubt, you can remove any containerd/docker unit files or drop-ins under /etc/systemd/system/ and restart…

**Comment by Jasper-Ben** [comment]
The systemd config I am using is:
https://raw.githubusercontent.com/kubernetes/release/v0.4.0/cmd/kubepkg/templates/latest/deb/kubelet/lib/systemd/system/kubelet.service 
and 
https://raw.githubusercontent.com/kubernetes/release/v0.4.0/cmd/kubepkg/templates/latest/deb/kubeadm/10-kubeadm.conf

and I'm not sure adding `--container-runtime=remote --container-runtime-endpoint=unix:///run/containerd/containerd.sock` actually makes any difference.

I noticed however, that kubeadm tries to save configuration files to /var, which of course would fail as it is ro:
```
[kubelet-start] Writing kubelet environment file with flags to file "/var/lib/kubelet/kubeadm-flags.env"
[kubelet-start] Writing kubelet configuration to file "/var/lib/kubelet/config.yaml"
```
So this is probably the reason why kubelet does not enter a healthy state and therefore an issue independent from dockershim vs. containerd.

**Comment by pothos** [comment]
`/var` is not read-only but `/usr`: https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/troubleshooting-kubeadm/#usr-mounted-read-only

**Comment by Jasper-Ben** [comment]
> `/var` is not read-only but `/usr`: https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/troubleshooting-kubeadm/#usr-mounted-read-only

whoops, my bad...

well, then I have no clue what the issue might be here. But at least I can confirm that `--container-runtime=remote --container-runtime-endpoint=unix:///run/containerd/containerd.sock` are added by kubeadm init, so there is no need to modify the default kubelet systemd service, as indicated by a dry-run:

```
[dryrun] Would write file "/var/lib/kubelet/kubeadm-flags.env" with content:
        KUBELET_KUBEADM_ARGS="--container-runtime=remote --container-runtime-endpoint=/run/containerd/containerd.sock"
```

At this point I'll just assume that something messed up during one of my many retries, as I already had a functioning cluster at some point (although still using dockershim). I'll just do a clean install tomorrow and see if that makes any difference.

**Comment by pothos** [comment]
There you also can find this: https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/troubleshooting-kubeadm/#kubeadm-reset-unmounts-var-lib-kubelet
You can create a new issue if you discover a problem.

About the default args, thanks, then it's really nothing special to take care of but the flex-volume I hope ;)

**Comment by Jasper-Ben** [comment]
> There you also can find this: https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/troubleshooting-kubeadm/#kubeadm-reset-unmounts-var-lib-kubelet
> You can create a new issue if you discover a problem.
> 
> About the default args, thanks, then it's really nothing special to take care of but the flex-volume I hope ;)

I am using v1.20, so this issue should be fixed. I am not sure how well kubeadm handles early aborts during the init phase, which I might have done once or twice :innocent:

**Comment by Jasper-Ben** [comment]
@pothos: followup: after reinstalling the OS the kubernetes cluster installed without any issues. One minor nitpick though: At least in the current stable release the containerd service is not enabled by default (at least after masking the docker service). Other than that... it's so simple now! :+1: 

edit: s/systemd/containerd/g
