### ISSUE TITLE
Please modify coreos related fields in flatcar_production_vmware_ova.ovf as flatcar related items

### ISSUE THREAD

**Issue by Winnie81** [flatcar/Flatcar#68]
flatcar_production_vmware_ova.ovf contains several "coreos" related items, such as "CoreOS config data", "CoreOS config url" and "CoreOS config data encoding". They should be flatcar related.

**Comment by pothos** [comment]
The generic `ignition.config.data` parameters are now supported and the preferred way. The `coreos.config.data` parameters are there for backwards compatibility and easy migration.
Please reopen this issue if you find a problem.

**Comment by Winnie81** [comment]
> The generic `ignition.config.data` parameters are now supported and the preferred way. The `coreos.config.data` parameters are there for backwards compatibility and easy migration.
> Please reopen this issue if you find a problem.

These fields will appear in vSphere Web Client when deploying Flatcar, and it is confusing for customers. So please fix it.

**Comment by Winnie81** [comment]
@pothos Please help me reopen it. I couldn't open it.

**Comment by pothos** [comment]
For command line invocation with `ovftool` removing the CoreOS variable is a breaking change during migration. So a good point to remove the variables would be after the CoreOS EOL in end of May.

**Comment by t-lo** [comment]
Hello @Winnie81 

I'd like to stress that our main motivation for remaining with the status quo at this point is to help users seamlessly migrate from CoreOS Container Linux. As CoreOS Container Linux will be EOL rather very soon users are on a tight timeline, that's why we'd like to remain a drop-in replacement for the time being.

That said, we are aware that we have a number of legacy naming issues in Flatcar Container Linux, and we are planning to address these - retiring the old naming with due process - after CoreOS container Linux met EOL.

**Comment by Winnie81** [comment]
Got it. Thanks.
@t-lo

**Comment by pothos** [comment]
There is some progress on this. https://github.com/flatcar-linux/ignition/pull/11 fixes support for both guest variables. In https://github.com/flatcar-linux/scripts/pull/56 the old variables are removed from the OVF metadata (and thus the web UI) but will continue to work when specified via `ovftool --X:guest:coreos.config.…` for backwards compatibility.

**Comment by pothos** [comment]
With the current releases this problem should be solved, closing.

**Comment by Winnie81** [comment]
> With the current releases this problem should be solved, closing.

For 2592.0.0, the CoreOS related items still exist and the default user is "coreos", please reopen and fix it. Thanks.

**Comment by pothos** [comment]
Hi,
the default user being `coreos` probably won't change as Flatcar is a CoreOS Container Linux drop-in.
What related items can we improve? The only mentioning left should be `coreos-cloudinit` in the field explanations which refers to a particular cloud-init implementation.
https://github.com/flatcar-linux/scripts/blob/main/build_library/template_vmware.ovf

**Comment by Winnie81** [comment]
> Hi,
> the default user being `coreos` probably won't change as Flatcar is a CoreOS Container Linux drop-in.
> What related items can we improve? The only mentioning left should be `coreos-cloudinit` in the field explanations which refers to a particular cloud-init implementation.
> https://github.com/flatcar-linux/scripts/blob/main/build_library/template_vmware.ovf

"coreos" related items, such as "CoreOS config data", "CoreOS config url" and "CoreOS config data encoding", can they be modified?

**Comment by pothos** [comment]
That were the old field and the current versions don't have them. Here e.g. Stable: https://stable.release.flatcar-linux.net/amd64-usr/current/flatcar_production_vmware_ova.ovf

**Comment by Winnie81** [comment]
I checked it with 2592.0.0, they still exist. And for  https://stable.release.flatcar-linux.net/amd64-usr/current/flatcar_production_vmware_ova.ovf, I can see "Ignition/coreos-cloudinit data" .

**Comment by Winnie81** [comment]
@t-lo @pothos  CoreOS has met EOL one year ago, but in the latest release 3139.2.0, " Ignition/coreos-cloudinit data", "Ignition/coreos-cloudinit data encoding" still exist, do you have any plan to fix it? If so, please reopen this issue. Thanks a lot.

**Comment by pothos** [comment]
`coreos-cloudinit` is the name of the cloud-init implementation. There are also other appearances with "coreos" in variable names that won't go away any time soon for backwards compatibility.
